services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  api_server:
    build:
      context: api_server

    environment:
      SQL_HOST: "mysql"
      SQL_PORT: 3306
      SQL_USERNAME: "root"
      SQL_PASSWORD: "root"
      SQL_DATABASE: "digital_hunter"

    ports:
      - "8085:8085"


volumes:
  mysql_data:
